import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        // January 2026 - 10 transactions
        {
            date: '2026-01-05',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian 5 unit laptop Dell Latitude untuk karyawan baru divisi IT',
            amount: 75000000,
            status: 'approved',
            poNumber: 'PO-2026-001',
            warranty: 'Ada',
            expiredWarranty: '2029-01-05',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-05T08:30:00').toISOString(),
            updatedAt: new Date('2026-01-05T14:20:00').toISOString(),
        },
        {
            date: '2026-01-08',
            vendor: 'PT Microsoft Indonesia',
            category: 'Software',
            description: 'Lisensi Microsoft 365 Business Premium untuk 50 user',
            amount: 45000000,
            status: 'approved',
            poNumber: 'PO-2026-002',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-01-08',
            createdAt: new Date('2026-01-08T09:15:00').toISOString(),
            updatedAt: new Date('2026-01-08T16:45:00').toISOString(),
        },
        {
            date: '2026-01-12',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Upgrade bandwidth internet dedicated dari 100 Mbps ke 500 Mbps',
            amount: 35000000,
            status: 'approved',
            poNumber: 'PO-2026-003',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-12T10:00:00').toISOString(),
            updatedAt: new Date('2026-01-12T15:30:00').toISOString(),
        },
        {
            date: '2026-01-15',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Jasa konsultasi implementasi sistem ERP SAP untuk perusahaan',
            amount: 85000000,
            status: 'approved',
            poNumber: 'PO-2026-004',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-15T08:45:00').toISOString(),
            updatedAt: new Date('2026-01-15T17:00:00').toISOString(),
        },
        {
            date: '2026-01-18',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Server HP ProLiant DL380 Gen11 untuk data center',
            amount: 95000000,
            status: 'pending',
            poNumber: 'PO-2026-005',
            warranty: 'Ada',
            expiredWarranty: '2029-01-18',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-18T11:20:00').toISOString(),
            updatedAt: new Date('2026-01-18T11:20:00').toISOString(),
        },
        {
            date: '2026-01-20',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Pengembangan fitur baru portal employee self-service dan hosting tahunan',
            amount: 28000000,
            status: 'approved',
            poNumber: 'PO-2026-006',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-01-20',
            createdAt: new Date('2026-01-20T09:30:00').toISOString(),
            updatedAt: new Date('2026-01-20T14:15:00').toISOString(),
        },
        {
            date: '2026-01-23',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Pelatihan AWS Solutions Architect Associate untuk 10 engineer',
            amount: 42000000,
            status: 'approved',
            poNumber: 'PO-2026-007',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-23T10:15:00').toISOString(),
            updatedAt: new Date('2026-01-23T16:00:00').toISOString(),
        },
        {
            date: '2026-01-25',
            vendor: 'PT Adobe Indonesia',
            category: 'Software',
            description: 'Lisensi Adobe Creative Cloud All Apps untuk tim desain grafis',
            amount: 18000000,
            status: 'approved',
            poNumber: 'PO-2026-008',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-01-25',
            createdAt: new Date('2026-01-25T08:00:00').toISOString(),
            updatedAt: new Date('2026-01-25T13:45:00').toISOString(),
        },
        {
            date: '2026-01-28',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Storage NAS Synology DS1821+ 8-bay untuk backup dan arsip data',
            amount: 52000000,
            status: 'pending',
            poNumber: 'PO-2026-009',
            warranty: 'Ada',
            expiredWarranty: '2029-01-28',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-28T09:45:00').toISOString(),
            updatedAt: new Date('2026-01-28T09:45:00').toISOString(),
        },
        {
            date: '2026-01-30',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Audit keamanan sistem dan penetration testing infrastruktur IT',
            amount: 38000000,
            status: 'rejected',
            poNumber: 'PO-2026-010',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-01-30T10:30:00').toISOString(),
            updatedAt: new Date('2026-01-30T15:20:00').toISOString(),
        },

        // February 2026 - 10 transactions
        {
            date: '2026-02-03',
            vendor: 'PT Oracle Indonesia',
            category: 'Software',
            description: 'Perpanjangan lisensi Oracle Database Enterprise Edition 19c',
            amount: 92000000,
            status: 'approved',
            poNumber: 'PO-2026-011',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-02-03',
            createdAt: new Date('2026-02-03T08:15:00').toISOString(),
            updatedAt: new Date('2026-02-03T14:30:00').toISOString(),
        },
        {
            date: '2026-02-05',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya colocation 2 rack server di data center Tier 3 Cyber Building',
            amount: 48000000,
            status: 'approved',
            poNumber: 'PO-2026-012',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-02-05T09:00:00').toISOString(),
            updatedAt: new Date('2026-02-05T16:15:00').toISOString(),
        },
        {
            date: '2026-02-08',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Pembelian 15 unit monitor Dell UltraSharp 27 inch untuk office',
            amount: 32000000,
            status: 'approved',
            poNumber: 'PO-2026-013',
            warranty: 'Ada',
            expiredWarranty: '2029-02-08',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-02-08T10:30:00').toISOString(),
            updatedAt: new Date('2026-02-08T15:45:00').toISOString(),
        },
        {
            date: '2026-02-11',
            vendor: 'PT Atlassian Indonesia',
            category: 'Software',
            description: 'Lisensi Jira Software dan Confluence Data Center untuk 100 user',
            amount: 55000000,
            status: 'approved',
            poNumber: 'PO-2026-014',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-02-11',
            createdAt: new Date('2026-02-11T08:45:00').toISOString(),
            updatedAt: new Date('2026-02-11T14:00:00').toISOString(),
        },
        {
            date: '2026-02-14',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Sertifikasi Cisco CCNA dan CCNP untuk 5 network engineer',
            amount: 68000000,
            status: 'pending',
            poNumber: 'PO-2026-015',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-02-14T09:15:00').toISOString(),
            updatedAt: new Date('2026-02-14T09:15:00').toISOString(),
        },
        {
            date: '2026-02-17',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'SSL certificate wildcard dan security hardening untuk website corporate',
            amount: 12000000,
            status: 'approved',
            poNumber: 'PO-2026-016',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-02-17',
            createdAt: new Date('2026-02-17T10:00:00').toISOString(),
            updatedAt: new Date('2026-02-17T15:30:00').toISOString(),
        },
        {
            date: '2026-02-20',
            vendor: 'PT VMware Indonesia',
            category: 'Software',
            description: 'Lisensi VMware vSphere Enterprise Plus untuk virtualisasi server',
            amount: 78000000,
            status: 'approved',
            poNumber: 'PO-2026-017',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date('2026-02-20T08:30:00').toISOString(),
            updatedAt: new Date('2026-02-20T14:45:00').toISOString(),
        },
        {
            date: '2026-02-23',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Maintenance dan support server tahunan untuk 20 server production',
            amount: 64000000,
            status: 'pending',
            poNumber: 'PO-2026-018',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-02-23T09:45:00').toISOString(),
            updatedAt: new Date('2026-02-23T09:45:00').toISOString(),
        },
        {
            date: '2026-02-25',
            vendor: 'PT Kaspersky Indonesia',
            category: 'Software',
            description: 'Lisensi Kaspersky Endpoint Security for Business Advanced 200 user',
            amount: 25000000,
            status: 'approved',
            poNumber: 'PO-2026-019',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2027-02-25',
            createdAt: new Date('2026-02-25T10:15:00').toISOString(),
            updatedAt: new Date('2026-02-25T16:00:00').toISOString(),
        },
        {
            date: '2026-02-27',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Workshop Kubernetes, Docker, dan DevOps untuk tim development',
            amount: 38000000,
            status: 'approved',
            poNumber: 'PO-2026-020',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2026-02-27T08:00:00').toISOString(),
            updatedAt: new Date('2026-02-27T13:30:00').toISOString(),
        },
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});