import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        {
            date: '2024-01-15',
            vendor: 'Dell Technologies',
            category: 'Hardware',
            description: '5x Dell PowerEdge R750 servers for data center',
            amount: 45000,
            status: 'approved',
            poNumber: 'PO-2024-001',
            warranty: 'Ada',
            expiredWarranty: '2027-01-15',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-01-20',
            vendor: 'Microsoft',
            category: 'Software',
            description: 'Annual Microsoft 365 E5 licenses for 200 users',
            amount: 32000,
            status: 'approved',
            poNumber: 'PO-2024-002',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-01-20',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-02-05',
            vendor: 'AWS',
            category: 'Infrastructure',
            description: 'Monthly AWS cloud infrastructure services',
            amount: 28500,
            status: 'approved',
            poNumber: 'PO-2024-003',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-02-12',
            vendor: 'Cisco Systems',
            category: 'Hardware',
            description: '10x Cisco Catalyst 9300 switches',
            amount: 52000,
            status: 'approved',
            poNumber: 'PO-2024-004',
            warranty: 'Ada',
            expiredWarranty: '2027-02-12',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-02-18',
            vendor: 'Salesforce',
            category: 'Software',
            description: 'Salesforce Enterprise Edition annual subscription',
            amount: 18500,
            status: 'approved',
            poNumber: 'PO-2024-005',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-02-18',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-03-01',
            vendor: 'Google Cloud',
            category: 'Website',
            description: 'Annual website hosting and CDN services',
            amount: 12000,
            status: 'approved',
            poNumber: 'PO-2024-006',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-03-01',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-03-10',
            vendor: 'Oracle',
            category: 'Software',
            description: 'Oracle Database Enterprise Edition perpetual license',
            amount: 48000,
            status: 'approved',
            poNumber: 'PO-2024-007',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-03-15',
            vendor: 'IBM',
            category: 'Personnel',
            description: 'Cloud architecture certification training for 5 staff',
            amount: 8500,
            status: 'approved',
            poNumber: 'PO-2024-008',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-04-01',
            vendor: 'VMware',
            category: 'Infrastructure',
            description: 'VMware vSphere Enterprise Plus subscription',
            amount: 22000,
            status: 'pending',
            poNumber: 'PO-2024-009',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-04-08',
            vendor: 'Dell Technologies',
            category: 'Hardware',
            description: '20x Dell Latitude 7440 laptops for new hires',
            amount: 35000,
            status: 'pending',
            poNumber: 'PO-2024-010',
            warranty: 'Ada',
            expiredWarranty: '2027-04-08',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-04-12',
            vendor: 'Adobe',
            category: 'Software',
            description: 'Adobe Creative Cloud for Teams - 15 licenses',
            amount: 9500,
            status: 'approved',
            poNumber: 'PO-2024-011',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-04-12',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-04-18',
            vendor: 'Cisco Systems',
            category: 'Services',
            description: 'Annual managed security services and monitoring',
            amount: 42000,
            status: 'pending',
            poNumber: 'PO-2024-012',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-05-01',
            vendor: 'AWS',
            category: 'Website',
            description: 'Corporate website redesign and development',
            amount: 25000,
            status: 'rejected',
            poNumber: 'PO-2024-013',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-05-05',
            vendor: 'Cisco Systems',
            category: 'Hardware',
            description: 'Firewall and VPN equipment upgrade',
            amount: 38000,
            status: 'pending',
            poNumber: 'PO-2024-014',
            warranty: 'Tidak Ada',
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            date: '2024-05-10',
            vendor: 'Microsoft',
            category: 'Services',
            description: 'Azure migration consulting and implementation',
            amount: 55000,
            status: 'approved',
            poNumber: 'PO-2024-015',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});