import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        {
            date: '2025-01-05',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian 10 unit laptop Dell Latitude untuk karyawan baru divisi IT',
            amount: 85000000,
            status: 'approved',
            poNumber: 'PO-2025-001',
            warranty: 'Ada',
            expiredWarranty: '2028-01-05',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-01-05').toISOString(),
            updatedAt: new Date('2025-01-05').toISOString(),
        },
        {
            date: '2025-01-12',
            vendor: 'PT Microsoft Indonesia',
            category: 'Software',
            description: 'Lisensi Microsoft 365 Business Premium untuk 50 user',
            amount: 45000000,
            status: 'approved',
            poNumber: 'PO-2025-002',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-01-12',
            createdAt: new Date('2025-01-12').toISOString(),
            updatedAt: new Date('2025-01-12').toISOString(),
        },
        {
            date: '2025-01-18',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Pelatihan AWS Cloud Architect untuk 5 staff IT',
            amount: 35000000,
            status: 'approved',
            poNumber: 'PO-2025-003',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-01-18').toISOString(),
            updatedAt: new Date('2025-01-18').toISOString(),
        },
        {
            date: '2025-01-25',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya AWS cloud computing bulan Januari 2025',
            amount: 28000000,
            status: 'approved',
            poNumber: 'PO-2025-004',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-01-25').toISOString(),
            updatedAt: new Date('2025-01-25').toISOString(),
        },
        {
            date: '2025-02-03',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Hosting dan domain tahunan website perusahaan',
            amount: 12000000,
            status: 'approved',
            poNumber: 'PO-2025-005',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-02-03',
            createdAt: new Date('2025-02-03').toISOString(),
            updatedAt: new Date('2025-02-03').toISOString(),
        },
        {
            date: '2025-02-10',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Server Dell PowerEdge R750 untuk data center',
            amount: 95000000,
            status: 'approved',
            poNumber: 'PO-2025-006',
            warranty: 'Ada',
            expiredWarranty: '2028-02-10',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-02-10').toISOString(),
            updatedAt: new Date('2025-02-10').toISOString(),
        },
        {
            date: '2025-02-15',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Jasa konsultasi implementasi sistem ERP perusahaan',
            amount: 75000000,
            status: 'approved',
            poNumber: 'PO-2025-007',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-02-15').toISOString(),
            updatedAt: new Date('2025-02-15').toISOString(),
        },
        {
            date: '2025-02-22',
            vendor: 'PT Oracle Indonesia',
            category: 'Software',
            description: 'Lisensi Oracle Database Enterprise Edition',
            amount: 100000000,
            status: 'pending',
            poNumber: 'PO-2025-008',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date('2025-02-22').toISOString(),
            updatedAt: new Date('2025-02-22').toISOString(),
        },
        {
            date: '2025-03-01',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Upgrade bandwidth internet dedicated dari 100 Mbps ke 500 Mbps',
            amount: 42000000,
            status: 'approved',
            poNumber: 'PO-2025-009',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-03-01').toISOString(),
            updatedAt: new Date('2025-03-01').toISOString(),
        },
        {
            date: '2025-03-08',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian 20 unit monitor Dell UltraSharp 27 inch',
            amount: 32000000,
            status: 'approved',
            poNumber: 'PO-2025-010',
            warranty: 'Ada',
            expiredWarranty: '2027-03-08',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-03-08').toISOString(),
            updatedAt: new Date('2025-03-08').toISOString(),
        },
        {
            date: '2025-03-15',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Sertifikasi CCNA Cisco untuk 3 staff tim network',
            amount: 18000000,
            status: 'approved',
            poNumber: 'PO-2025-011',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-03-15').toISOString(),
            updatedAt: new Date('2025-03-15').toISOString(),
        },
        {
            date: '2025-03-22',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Pengembangan fitur baru web portal karyawan',
            amount: 55000000,
            status: 'approved',
            poNumber: 'PO-2025-012',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-09-22',
            createdAt: new Date('2025-03-22').toISOString(),
            updatedAt: new Date('2025-03-22').toISOString(),
        },
        {
            date: '2025-03-28',
            vendor: 'PT Adobe Indonesia',
            category: 'Software',
            description: 'Perpanjangan lisensi Adobe Creative Cloud untuk tim desain',
            amount: 24000000,
            status: 'approved',
            poNumber: 'PO-2025-013',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-03-28',
            createdAt: new Date('2025-03-28').toISOString(),
            updatedAt: new Date('2025-03-28').toISOString(),
        },
        {
            date: '2025-04-05',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Maintenance annual untuk sistem backup dan disaster recovery',
            amount: 38000000,
            status: 'approved',
            poNumber: 'PO-2025-014',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-04-05').toISOString(),
            updatedAt: new Date('2025-04-05').toISOString(),
        },
        {
            date: '2025-04-12',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Storage NAS Synology untuk backup data departemen',
            amount: 48000000,
            status: 'approved',
            poNumber: 'PO-2025-015',
            warranty: 'Ada',
            expiredWarranty: '2028-04-12',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-04-12').toISOString(),
            updatedAt: new Date('2025-04-12').toISOString(),
        },
        {
            date: '2025-04-18',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya AWS cloud computing bulan April 2025',
            amount: 31000000,
            status: 'approved',
            poNumber: 'PO-2025-016',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-04-18').toISOString(),
            updatedAt: new Date('2025-04-18').toISOString(),
        },
        {
            date: '2025-04-25',
            vendor: 'PT Atlassian Indonesia',
            category: 'Software',
            description: 'Lisensi Jira dan Confluence untuk manajemen project',
            amount: 22000000,
            status: 'pending',
            poNumber: 'PO-2025-017',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-04-25',
            createdAt: new Date('2025-04-25').toISOString(),
            updatedAt: new Date('2025-04-25').toISOString(),
        },
        {
            date: '2025-05-02',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Workshop Kubernetes dan Docker untuk tim DevOps',
            amount: 28000000,
            status: 'approved',
            poNumber: 'PO-2025-018',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-05-02').toISOString(),
            updatedAt: new Date('2025-05-02').toISOString(),
        },
        {
            date: '2025-05-10',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian 5 unit printer laser HP LaserJet Enterprise',
            amount: 25000000,
            status: 'approved',
            poNumber: 'PO-2025-019',
            warranty: 'Ada',
            expiredWarranty: '2027-05-10',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-05-10').toISOString(),
            updatedAt: new Date('2025-05-10').toISOString(),
        },
        {
            date: '2025-05-15',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Implementasi SSL certificate dan security enhancement',
            amount: 15000000,
            status: 'approved',
            poNumber: 'PO-2025-020',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-05-15',
            createdAt: new Date('2025-05-15').toISOString(),
            updatedAt: new Date('2025-05-15').toISOString(),
        },
        {
            date: '2025-05-22',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Audit keamanan sistem informasi perusahaan',
            amount: 52000000,
            status: 'approved',
            poNumber: 'PO-2025-021',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-05-22').toISOString(),
            updatedAt: new Date('2025-05-22').toISOString(),
        },
        {
            date: '2025-05-28',
            vendor: 'PT VMware Indonesia',
            category: 'Software',
            description: 'Lisensi VMware vSphere untuk virtualisasi server',
            amount: 68000000,
            status: 'rejected',
            poNumber: 'PO-2025-022',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date('2025-05-28').toISOString(),
            updatedAt: new Date('2025-05-28').toISOString(),
        },
        {
            date: '2025-06-03',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Upgrade RAM server dari 64GB ke 256GB',
            amount: 42000000,
            status: 'approved',
            poNumber: 'PO-2025-023',
            warranty: 'Ada',
            expiredWarranty: '2027-06-03',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-06-03').toISOString(),
            updatedAt: new Date('2025-06-03').toISOString(),
        },
        {
            date: '2025-06-10',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya colocation server di data center Tier 3',
            amount: 58000000,
            status: 'approved',
            poNumber: 'PO-2025-024',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-06-10').toISOString(),
            updatedAt: new Date('2025-06-10').toISOString(),
        },
        {
            date: '2025-06-15',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Pelatihan cybersecurity dan ethical hacking untuk tim security',
            amount: 45000000,
            status: 'approved',
            poNumber: 'PO-2025-025',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-06-15').toISOString(),
            updatedAt: new Date('2025-06-15').toISOString(),
        },
        {
            date: '2025-06-22',
            vendor: 'PT Kaspersky Indonesia',
            category: 'Software',
            description: 'Lisensi Kaspersky Endpoint Security untuk 100 endpoints',
            amount: 35000000,
            status: 'approved',
            poNumber: 'PO-2025-026',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-06-22',
            createdAt: new Date('2025-06-22').toISOString(),
            updatedAt: new Date('2025-06-22').toISOString(),
        },
        {
            date: '2025-06-28',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Maintenance dan update CMS website perusahaan',
            amount: 18000000,
            status: 'approved',
            poNumber: 'PO-2025-027',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2025-12-28',
            createdAt: new Date('2025-06-28').toISOString(),
            updatedAt: new Date('2025-06-28').toISOString(),
        },
        {
            date: '2025-07-05',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian UPS APC Smart-UPS 3000VA untuk server room',
            amount: 38000000,
            status: 'approved',
            poNumber: 'PO-2025-028',
            warranty: 'Ada',
            expiredWarranty: '2028-07-05',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-07-05').toISOString(),
            updatedAt: new Date('2025-07-05').toISOString(),
        },
        {
            date: '2025-07-12',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Jasa migrasi database ke cloud infrastructure',
            amount: 72000000,
            status: 'pending',
            poNumber: 'PO-2025-029',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-07-12').toISOString(),
            updatedAt: new Date('2025-07-12').toISOString(),
        },
        {
            date: '2025-07-18',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya AWS cloud computing bulan Juli 2025',
            amount: 34000000,
            status: 'approved',
            poNumber: 'PO-2025-030',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-07-18').toISOString(),
            updatedAt: new Date('2025-07-18').toISOString(),
        },
        {
            date: '2025-07-25',
            vendor: 'PT JetBrains Indonesia',
            category: 'Software',
            description: 'Lisensi JetBrains All Products Pack untuk tim developer',
            amount: 28000000,
            status: 'approved',
            poNumber: 'PO-2025-031',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-07-25',
            createdAt: new Date('2025-07-25').toISOString(),
            updatedAt: new Date('2025-07-25').toISOString(),
        },
        {
            date: '2025-08-02',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Pembelian switch Cisco Catalyst 48-port untuk network upgrade',
            amount: 65000000,
            status: 'approved',
            poNumber: 'PO-2025-032',
            warranty: 'Ada',
            expiredWarranty: '2030-08-02',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-08-02').toISOString(),
            updatedAt: new Date('2025-08-02').toISOString(),
        },
        {
            date: '2025-08-08',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Bootcamp DevOps dan CI/CD untuk 8 staff IT',
            amount: 52000000,
            status: 'approved',
            poNumber: 'PO-2025-033',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-08-08').toISOString(),
            updatedAt: new Date('2025-08-08').toISOString(),
        },
        {
            date: '2025-08-15',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Optimasi SEO dan performance website perusahaan',
            amount: 22000000,
            status: 'approved',
            poNumber: 'PO-2025-034',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-02-15',
            createdAt: new Date('2025-08-15').toISOString(),
            updatedAt: new Date('2025-08-15').toISOString(),
        },
        {
            date: '2025-08-22',
            vendor: 'PT Veeam Indonesia',
            category: 'Software',
            description: 'Lisensi Veeam Backup & Replication untuk disaster recovery',
            amount: 48000000,
            status: 'pending',
            poNumber: 'PO-2025-035',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Perpetual',
            expiredSubscription: null,
            createdAt: new Date('2025-08-22').toISOString(),
            updatedAt: new Date('2025-08-22').toISOString(),
        },
        {
            date: '2025-08-28',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Implementasi monitoring system menggunakan Zabbix',
            amount: 38000000,
            status: 'approved',
            poNumber: 'PO-2025-036',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-08-28').toISOString(),
            updatedAt: new Date('2025-08-28').toISOString(),
        },
        {
            date: '2025-09-03',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Upgrade kapasitas storage cloud dari 10TB ke 50TB',
            amount: 68000000,
            status: 'approved',
            poNumber: 'PO-2025-037',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-09-03').toISOString(),
            updatedAt: new Date('2025-09-03').toISOString(),
        },
        {
            date: '2025-09-10',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian 15 unit keyboard dan mouse wireless Logitech',
            amount: 8500000,
            status: 'approved',
            poNumber: 'PO-2025-038',
            warranty: 'Tidak Ada',
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-09-10').toISOString(),
            updatedAt: new Date('2025-09-10').toISOString(),
        },
        {
            date: '2025-09-15',
            vendor: 'PT GitLab Indonesia',
            category: 'Software',
            description: 'Lisensi GitLab Ultimate untuk version control dan CI/CD',
            amount: 42000000,
            status: 'approved',
            poNumber: 'PO-2025-039',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-09-15',
            createdAt: new Date('2025-09-15').toISOString(),
            updatedAt: new Date('2025-09-15').toISOString(),
        },
        {
            date: '2025-09-22',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Sertifikasi Microsoft Azure Administrator untuk 4 staff cloud',
            amount: 32000000,
            status: 'approved',
            poNumber: 'PO-2025-040',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-09-22').toISOString(),
            updatedAt: new Date('2025-09-22').toISOString(),
        },
        {
            date: '2025-09-28',
            vendor: 'CV Solusi Digital',
            category: 'Website',
            description: 'Pengembangan mobile responsive design untuk semua halaman',
            amount: 48000000,
            status: 'pending',
            poNumber: 'PO-2025-041',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-03-28',
            createdAt: new Date('2025-09-28').toISOString(),
            updatedAt: new Date('2025-09-28').toISOString(),
        },
        {
            date: '2025-10-05',
            vendor: 'PT Indo Komputer',
            category: 'Hardware',
            description: 'Pembelian access point UniFi untuk coverage WiFi kantor',
            amount: 28000000,
            status: 'approved',
            poNumber: 'PO-2025-042',
            warranty: 'Ada',
            expiredWarranty: '2027-10-05',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-10-05').toISOString(),
            updatedAt: new Date('2025-10-05').toISOString(),
        },
        {
            date: '2025-10-12',
            vendor: 'CV Konsultan IT Nusantara',
            category: 'Services',
            description: 'Pentest dan vulnerability assessment sistem aplikasi',
            amount: 58000000,
            status: 'approved',
            poNumber: 'PO-2025-043',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-10-12').toISOString(),
            updatedAt: new Date('2025-10-12').toISOString(),
        },
        {
            date: '2025-10-18',
            vendor: 'PT Telkom Indonesia',
            category: 'Infrastructure',
            description: 'Biaya AWS cloud computing bulan Oktober 2025',
            amount: 36000000,
            status: 'approved',
            poNumber: 'PO-2025-044',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-10-18').toISOString(),
            updatedAt: new Date('2025-10-18').toISOString(),
        },
        {
            date: '2025-10-24',
            vendor: 'PT Tableau Indonesia',
            category: 'Software',
            description: 'Lisensi Tableau Desktop untuk business intelligence dan analytics',
            amount: 55000000,
            status: 'approved',
            poNumber: 'PO-2025-045',
            warranty: null,
            expiredWarranty: null,
            licenseType: 'Subscription',
            expiredSubscription: '2026-10-24',
            createdAt: new Date('2025-10-24').toISOString(),
            updatedAt: new Date('2025-10-24').toISOString(),
        },
        {
            date: '2025-10-28',
            vendor: 'PT Mitra Teknologi',
            category: 'Hardware',
            description: 'Pembelian webcam Logitech 4K untuk ruang meeting',
            amount: 12000000,
            status: 'rejected',
            poNumber: 'PO-2025-046',
            warranty: 'Ada',
            expiredWarranty: '2027-10-28',
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-10-28').toISOString(),
            updatedAt: new Date('2025-10-28').toISOString(),
        },
        {
            date: '2025-10-30',
            vendor: 'PT Cipta Karya Digital',
            category: 'Personnel',
            description: 'Workshop Agile Scrum Master certification untuk project manager',
            amount: 25000000,
            status: 'pending',
            poNumber: 'PO-2025-047',
            warranty: null,
            expiredWarranty: null,
            licenseType: null,
            expiredSubscription: null,
            createdAt: new Date('2025-10-30').toISOString(),
            updatedAt: new Date('2025-10-30').toISOString(),
        },
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});